---
name: How do I?
description: Ask a question around how to do a task using the CLI
title: "How Do I: "
labels: ["question"]
assignees: ["manchuck", "pardel", "dragonmantank"]
body:
 - type: input
   id: question
   attributes:
    label: How do I
    description: Ask the question on how to do X with Y
    placeholder: send a WhatsApp Message
   validations:
    required: true
 - type: dropdown
   id: product
   attributes:
    label: API/Product
    description: Which API or Product do yo need help with?
    multiple: false
    options:
     - "Applications"
     - "Authentication"
     - "Number Insights"
     - "Numbers"
     - "Pricing"
     - "SMS (Legacy)"
     - "Users"
     - "Other"
   validations:
    required: true
 - type: input
   id: cli_sample
   attributes:
    label: Command Sample
    description: If you have already tried running a command, please provide an
      example of the command (be sure to redact your API Key/Secret)
