---
name: How do I?
description: Ask a question about a command or how to do a task with the CLI
title: "How Do I: "
labels: ["question"]
assignees: ["manchuck", "pardel", "dragonmantank"]
body:
 - type: textarea
   id: question
   attributes:
    label: How do I
    description: Ask the question about a command or how to do something with the CLI
    placeholder: configure the CLI
   validations:
    required: true
 - type: input
   id: cli_version
   attributes:
    label: ClI Version
    description: Run `vonage --version`
