---
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "Triage"]
assignees: ["manchuck", "pardel", "dragonmantank"]
body:
 - type: dropdown
   id: node_version
   attributes:
    label: Node Version
    description: What version of NodeJS are you using?
    options:
     - 16.x
     - 18.x
     - 20.x
     - 21.x
   validations:
    required: true
 - type: dropdown
   id: platform
   attributes:
    label: Platform
    description: What is the platform you are having the issue on?
    multiple: true
    options:
     - "Windows (PowerShell)"
     - "Windows (Command line)"
     - "Linux"
     - "Mac (Intel)"
     - "Mac (Apple Silcon)"
   validations:
    required: true
 - type: input
   id: cli_version
   attributes:
    label: CLI Version
    description: What version of the CLI are you using? use `vonage --version`
      to get the version
    placeholder: 1.26.2
   validations:
    required: true
 - type: input
   id: Command
   attributes:
    label: Command
    description: Please provide the command you are running (be sure to redact
      your API Key/Secret
   validations:
    required: true
 - type: textarea
   id: expected_behavior
   attributes:
    label: Expected Behavior
    description: Please provide a brief description of what you wanted to
      happen
   validations:
    required: true
 - type: textarea
   id: actual_behavior
   attributes:
    label: Actual Behavior
    description: Please provide a brief description of what happened. It would
      be helpful to include the debug log by setting the `DEBUG` environment
      varialbe to `*` e.g. `DEBUG=* vonage apps:create`
   validations:
    required: true
