---
name: Vonage

on:
  push:
    branches: [2.x]
  pull_request:
jobs:
  test:
    env:
      NODE_NO_WARNINGS: 1
      NODE_OPTIONS: --experimental-vm-modules
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install typescript
        run: |
          npm install -g typescript
          npm install

      - name: Lint
        run: npm run lint

      - name: Compile, Test
        run: |
          npm run compile
          npm run test -- --coverage --verbose --maxWorkers=2

      - name: Run codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage
