name: Vonage

on:
  push:
    branches: [ 2.x ]
  pull_request:
jobs:
  test:
    env:
      NODE_NO_WARNINGS: 1
      NODE_OPTIONS: --experimental-vm-modules
    continue-on-error: ${{ matrix.experimental }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [16.x, 18.x, 20.x]
        experimental: [false]
        include:
          - os: ubuntu-latest
            node: 14
            experimental: true
            npm_version: "@8.3.1"
          - os: windows-latest
            node: 14
            experimental: true
            npm_version: "@8.3.1"
          - os: macos-latest
            node: 14
            experimental: true
            npm_version: "@8.3.1"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Install typescript
      run: npm install -g typescript npm${{ matrix.npm_version }} && npm install

    - name: Lint
      run: npm run lint

    - name: Compile, Test
      run: npm run compile && npm run test -- --coverage --verbose --maxWorkers=2

    - name: Run codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage
