---
name: Vonage

on:
  push:
    branches:
      - 3.x
  pull_request:

jobs:
  static:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install packages
        run: npm install

      - name: Lint
        run: npm run lint

  test:
    runs-on: ${{ matrix.os }}
    name: Test and build

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install packages
        run: npm install

      - name: Test
        env:
          JEST_JUNIT_CLASSNAME: "{filepath}"
        run: npm run test -- --coverage --reporters=jest-junit --reporters=default

      - name: Run codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
