---
name: Vonage

on:
  push:
  pull_request:

jobs:
  static:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install packages
        run: npm ci --ignore-scripts

      - name: Lint
        run: npm run lint

  test:
    runs-on: ${{ matrix.os }}
    name: Test and build

      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, windows-latest]
          node: [22.x, 24.x, 26.x]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install packages
        run: npm i --ignore-scripts

      - name: Test
        if: matrix.node != '22.x'
        run: NO_COLOR=1 node --test --test-reporter=spec --test-reporter-destination=stdout --import ./__tests__/setup.js

      - name: Test
        if: matrix.node == '22.x'
        run: NO_COLOR=1 node --test --experimental-test-coverage --test-reporter=junit --test-reporter-destination=./test-results/junit.xml --test-reporter=spec --test-reporter-destination=stdout --import ./__tests__/setup.js

      - name: Run codecov
        if: matrix.node == '22.x'
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage

      - name: Upload test results to Codecov
        if: matrix.node == '22.x' && ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: ./test-results/junit.xml
          token: ${{ secrets.CODECOV_TOKEN }}
