name: Publish to NPM

on:
  release:
    types:
      - published

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN_COMMIT }}

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Update Release

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: '3.x'
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_COMMIT }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
