name: Publish to NPM

on:
  release:
    types:
      - published

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN_COMMIT }}

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    name: Update Release

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: '3.x'
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  notify-release:
    runs-on: ubuntu-latest
    name: Notify Release
    strategy:
      matrix:
        url: [SLACK_WEBHOOK_ASK_DEVREL_URL, SLACK_WEBHOOK_DEVREL_TOOLING_URL, SLACK_WEBHOOK_DEVREL_PRIVATE_URL]
    steps:
      - name: Send to slack channles
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets[matrix.url]}}
          webhook-type: incoming-webhook
          errors: true
          payload: |
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: ":initial_external_notification_sent: Version ${{ github.event.release.name }} of the NodeJS SDK has been released"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "${{ github.event.release.body }}"
                  emoji: true
              - type: "divider"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "You can view the full change log <${{github.event.release.html_url }}|here>"
